package org.netbeans.bamboo.ui.wizard;

public class InstancePropertiesForm extends javax.swing.JPanel {

  /**
   * Creates new form InstancePropertiesForm
   */
  public InstancePropertiesForm() {
    initComponents();
  }

  public String getInstanceUrl() {
    return serverTextField.getText();
  }
  
  public void setInstanceUrl(final String url) {
    serverTextField.setText(url);
  }
  
  public String getInstanceName() {
    return nameTextField.getText();
  }
  
  public void setInstanceName(final String name) {
    nameTextField.setText(name);
  }
  
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    serverLabel = new javax.swing.JLabel();
    serverTextField = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    nameTextField = new javax.swing.JTextField();

    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/netbeans/bamboo/ui/wizard/Bundle"); // NOI18N
    serverLabel.setText(bundle.getString("LBL_SERVER")); // NOI18N

    jLabel1.setText(org.openide.util.NbBundle.getMessage(InstancePropertiesForm.class, "TXT_NAME")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(serverLabel)
            .addGap(4, 4, 4)
            .addComponent(serverTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(nameTextField)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(serverTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(serverLabel))
        .addContainerGap(234, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JTextField nameTextField;
  private javax.swing.JLabel serverLabel;
  private javax.swing.JTextField serverTextField;
  // End of variables declaration//GEN-END:variables
}
