name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: olafurpg/setup-scala@v2
      with:
        java-version: openjdk@1.8
    - name: Build with Maven
      run: mvn -q -B clean verify --file pom.xml
