name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: olafurpg/setup-scala@v2
      with:
        java-version: openjdk@1.11
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
